name: jyutping
description: A chinese character to jyutping package for Dart developers.
homepage: https://artvuu.group
repository: https://github.com/artvuu/jyutping-for-flutter
version: 0.1.0
environment:
  sdk: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
